module.exports = {

    logIn: 'a[class="nav__link nav__link--clickable"]',
    findMyRate: 'a[class="main-nav__cta-btn btn"]',
    firstName: '#basicInfo_firstName',
    lastName: '#basicInfo_lastName',
    state: '#state',
    email: '#reg-email',
    password: '#reg-password1',
    confirmPassword: '#password2',
    iAgree: '#consents',
    loginButton: '#login-btn',
    mortgageApplication: 'a[href="https://www.sofi.com/b/landing/start/MORT?isNewApp=true"]',
    // mailingAddress: '#addr_addr1',
    // apartment: '#addr_addr2',
    // city: '#addr_city',
    // zip: '#addr_zip',
    // cellNumber: '#primaryPhone',
    // communicationPolicyAgree: '#subscribedToTcpa',
    dobMonth: '#dobMonth',
    dobDay: '#dobDay',
    dobYear: '#dobYear',
    citizenship: "#citizenship",
    homeOwnership: "#housing_PARENT",
    noCollege: '#noCollege',
    ugName: '#ugName',
    ugProgramId: '#ugProgramId',
    graduationDate: '#ugEndMonth',
    graduationYear: '#ugGradYear',
    employerName: '#employerInfo_name',
    selfEmployedButton: '#selfEmployed',
    individualAnnIncome: '#totalIncome',
    yearsExperience: '#experience',
    checkMyRateButton: '#profileSubmitButton',
    appName1: '#jv-field-y1nvXfwA',
    appLastName: '#jv-field-yVnvXfwu',
    appPrefName: '#jv-field-y3nvXfwC',
    appFullName: '#jv-field-ybnvXfwK',
    appEmail: '#jv-field-ycnvXfwL',
    appPhone: '#jv-field-yTnvXfws',
    appCountry: '#jv-field-yXnvXfww',
    appAddress: '#jv-field-ySnvXfwr',
    appCity: '#jv-field-yanvXfwJ',
    appState: '#jv-field-y7nvXfwG',
    appZip: '#jv-field-y0nvXfwz',
    appDiploma: '#jv-field-y4nvXfwD',
    referralEmployee: '#jv-field-y6nvXfwF',
    authToWork: '#jv-field-yWnvXfwv',
    immigration: '#jv-field-y5nvXfwE',
    gender: '#jv-field-yZnvXfwy',
    race: '#jv-field-yYnvXfwx',
    veteran: '#jv-field-yUnvXfwt',
    jobTitle: '#position',
    startDate: '#startMonth',
    startYear: '#startYear',
    attachResumeButton: '#jv-add-attachment',
    attachFile: 'span[class="needsclick ng-scope ng-binding"]',
    mortgageRefi: '#mortgageType_Refi',
    occupancyType: '#occupancyType',
    propertyType: '#propertyType',
    subjectAddress: 'div[class="col-md-12"]',
    subjectCity: 'input[name="city"]',
    cashoutRefiState: 'id[name="state"]',
    proposedPropertyCounty: '#proposedPropertyCounty',
    subjectZip: '#zip',
    estPropValue: '#estimatedPropertyValue',
    currentMortBalance: '#mortgageBalance',
    hoaDues: '#hoaMonthlyDues',
    maritalStatus: '#maritalStatus',
    householdCount: '#householdCount',
    creditAuthorization: '#creditAuthorization_field',
    preApprovalFormButton: '#preapprovalFormButton',
    utahStateSelector: 'option[value="UT"]',












}